CREATE DATABASE Subway_Restaurant;

CREATE TABLE customers (
CustomerID SMALLINT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(255),
LastName VARCHAR(255),
CustomerPhone VARCHAR(255), 
CustomerEmail VARCHAR(255), 
Last_Update TIMESTAMP
 );